<?php

/**
 * @file
 * Manage breakpoints and breakpoint sets for responsive designs.
 */

use \Drupal\breakpoint\Breakpoint;
use \Drupal\breakpoint\BreakpointSet;

/**
 * Implements hook_enable().
 *
 * Import breakpoints from all enabled themes.
 */
function breakpoint_enable() {
  config_install_default_config('module', 'breakpoint');
  $themes = list_themes();
  breakpoint_themes_enabled(array_keys($themes));
}

/**
 * Implements hook_themes_enabled().
 *
 * Import breakpoints from all new enabled themes.
 *
 * @param array $theme_list
 *   An array of theme names.
 */
function breakpoint_themes_enabled($theme_list) {
  $themes = list_themes();
  foreach ($theme_list as $theme_key) {
    if ($themes[$theme_key]->status) {
      $theme_breakpoints = breakpoint_get_theme_breakpoint_list($theme_key);
      if (!empty($theme_breakpoints)) {
        $weight = 0;
        // Build a breakpoint set for each theme.
        $breakpointset = new BreakpointSet();
        $breakpointset->id = $theme_key;
        $breakpointset->label = $themes[$theme_key]->info['name'];
        $breakpointset->sourceType = Breakpoint::SOURCE_TYPE_THEME;
        foreach ($theme_breakpoints as $name => $mediaQuery) {
          $breakpoint = new Breakpoint;
          $breakpoint->name = $name;
          $breakpoint->label = ucfirst($name);
          $breakpoint->mediaQuery = $mediaQuery;
          $breakpoint->source = $theme_key;
          $breakpoint->sourceType = Breakpoint::SOURCE_TYPE_THEME;
          $breakpoint->status = TRUE;
          $breakpoint->weight = $weight++;
          $breakpoint->save();
          $breakpointset->breakpoints[$breakpoint->id()] = $breakpoint;
        }
        $breakpointset->save();

        $uri = $breakpointset->uri();
        if ($uri) {
          $uri_options = $uri;
          unset($uri_options['path']);
          $uri = $uri['path'];
        }
        $message = t('The breakpoints from theme %theme are imported.', array(
          '%theme' => check_plain($themes[$theme_key]->info['name']),
        ));
        if (module_exists('breakpoint_ui') && $uri) {
          $message .= '<p>' . l(t('A new breakpoint set is created for theme %theme.', array(
            '%theme' => check_plain($themes[$theme_key]->info['name']),
          )), $uri, $uri_options);
        }
        drupal_set_message($message, 'status');
      }
    }
  }
}

/**
 * Implements hook_themes_disabled().
 *
 * Remove breakpoints from all disabled themes.
 *
 * @param array $theme_list
 *   An array of theme names.
 */
function breakpoint_themes_disabled($theme_list) {
  $breakpointsets = entity_load_multiple('breakpoint_breakpointset', $theme_list);
  foreach ($breakpointsets as $breakpointset) {
    $breakpointset->delete();
    // delete all breakpoints defined by this theme.
    $names = drupal_container()->get('config.storage')->listAll('breakpoints.breakpoint.' . Breakpoint::SOURCE_TYPE_THEME . '.' . $breakpointset->id() . '.');
    $entity_info = entity_get_info('breakpoint_breakpoint');

    foreach ($names as &$name) {
      $name = substr($name, strlen($entity_info['config prefix']) + 1);
    }
    $breakpoints = entity_load_multiple('breakpoint_breakpoint', $names);

    foreach ($breakpoints as $breakpoint) {
      $breakpoint->delete();
    }
  }
}

/**
 * Load general settings.
 */
function breakpoint_settings() {
  $config = config('breakpoint');
  if ($config->isNew()) {
    return FALSE;
  }
  return (object)$config->get();
}

/**
 * Save multipliers to settings.
 *
 * @param array $multipliers
 *   array containing multipliers.
 */
function breakpoint_settings_save_multipliers($multipliers) {
  $config = config('breakpoint');
  $config->set('multipliers', $multipliers);
  $config->save();
}

/**
 * Reload breakpoint sets as they were defined in the theme.
 *
 * @param string $theme_key
 *   The name of the theme.
 *
 * @return BreakpointSet
 *   Returns a BreakpointSet containing the breakpoints defined by the theme.
 */
function breakpoint_breakpointset_reload_from_theme($theme_key) {
  // Clear caches so theme.info is fresh.
  system_rebuild_theme_data();
  drupal_theme_rebuild();

  $themes = list_themes();
  if ($themes[$theme_key]->status) {
    $theme_breakpoints = breakpoint_get_theme_breakpoint_list($theme_key);
    if (!empty($theme_breakpoints)) {
      $weight = 0;
      // Build a set for each theme
      $breakpointset = new BreakpointSet();
      $breakpointset->id = $theme_key;
      $breakpointset->label = $themes[$theme_key]->info['name'];
      $breakpointset->sourceType = Breakpoint::SOURCE_TYPE_THEME;
      foreach ($theme_breakpoints as $name => $mediaQuery) {
        $breakpoint = new Breakpoint;
        $breakpoint->name = $name;
        $breakpoint->label = ucfirst($name);
        $breakpoint->mediaQuery = $mediaQuery;
        $breakpoint->source = $theme_key;
        $breakpoint->sourceType = Breakpoint::SOURCE_TYPE_THEME;
        $breakpoint->status = TRUE;
        $breakpoint->weight = $weight++;
        $breakpoint->save();
        $breakpointset->breakpoints[$breakpoint->getConfigName()] = $breakpoint;
      }
    }
    return $breakpointset;
  }
  return FALSE;
}

/**
 * Get a list of available breakpoints from a specified theme.
 *
 * @param $theme_key
 *   The name of the theme.
 *
 * @return
 *   An array of breakpoints in the form $breakpoint['name'] = 'media query'.
 */
function breakpoint_get_theme_breakpoint_list($theme_key) {
  $themes = list_themes();
  if (!isset($themes[$theme_key])) {
    return array();
  }

  $config = config($theme_key . '.breakpoints');
  if ($config) {
    return $config->get();
  }
  return array();
}

/**
 * Implements hook_entity_info().
 */
function breakpoint_entity_info() {
  // Breakpoint
  $types['breakpoint_breakpoint'] = array(
    'label' => 'Breakpoint',
    'entity class' => 'Drupal\breakpoint\Breakpoint',
    'controller class' => 'Drupal\Core\Config\Entity\ConfigStorageController',
    'config prefix' => 'breakpoint.breakpoint',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'label',
      'uuid' => 'uuid',
    ),
  );

  // Breakpointset
  $types['breakpoint_breakpointset'] = array(
    'label' => 'Breakpoint Set',
    'entity class' => 'Drupal\breakpoint\BreakpointSet',
    'controller class' => 'Drupal\breakpoint\BreakpointSetController',
    'config prefix' => 'breakpoint.breakpointset',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'label',
      'uuid' => 'uuid',
    ),
  );

  return $types;
}

/**
 * Load one breakpoint set by its identifier.
 */
function breakpoint_breakpointset_load($id) {
  return entity_load('breakpoint_breakpointset', $id);
}

/**
 * Load all breakpoint sets.
 */
function breakpoint_breakpointset_load_all() {
  $breakpointsets = entity_load_multiple('breakpoint_breakpointset');
  return $breakpointsets;
}

/**
 * Load one breakpoint by its identifier.
 */
function breakpoint_breakpoint_load($id) {
  return entity_load('breakpoint_breakpoint', $id);
}

/**
 * Load all breakpoints.
 */
function breakpoint_breakpoint_load_all() {
  $breakpoints = entity_load_multiple('breakpoint_breakpoint');
  return $breakpoints;
}

/**
 * Load all breakpointsets as select options.
 */
function breakpoint_breakpointset_select_options() {
  $options = array();
  $breakpointsets = breakpoint_breakpointset_load_all();
  foreach ($breakpointsets as $breakpointset) {
    $options[$breakpointset->id()] = $breakpointset->label();
  }
  return $options;
}
